config/routes.rb
Rails.application.routes.draw do
  get 'post/index'
  get 'post/dashboard'
  get 'post/create'

  root "post#index"

  get 'index/dashboard'
  get 'index/create'



  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord

    validates :title, presence:true
    validates :content, presence:true
    validates :image_url, presence:true

    before_save :chao_spoiler

    def chao_spoiler
        self.content = self.content.gsub("spoiler", " ")
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def dashboard
  end

  def create
  end
end

app/controllers/post_controller.rb
class PostController < ApplicationController

  http_basic_authenticate_with name: "desafiovamoscontodo", password: "XAHTJEAS23123%23", only: :dashboard

  def index
    @posts = Post.order("created_at DESC")
  end

  def dashboard
  end

  def create
    @post = Post.create(title: params[:title], content: params[:content],image_url: params[:image_url])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/post_helper.rb
module PostHelper
end

app/views/index/create.html.erb
<h1>Index#create</h1>
<p>Find me in app/views/index/create.html.erb</p>

app/views/index/dashboard.html.erb
<h1>Index#dashboard</h1>
<p>Find me in app/views/index/dashboard.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/post/create.html.erb
<% if @post.errors.any? %>
   <div id="create_posts">
       <h2>
          Errores Encontrados <%= pluralize(@post.errors.count, "") %>
          <br>
          <br>
          No se puede guardar el registro ... Que penita...
        </h2>
        <ul>
           <% @post.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
        </ul>
    </div>
<% else %>
   <h1>Registro exitoso...</h1>
   <h2>Felicitaciones...</h2>
<% end %>

<button type="button"><%= link_to "Volver", :back %> </button>
<button type="button"><%= link_to "Ir al Posteos", root_path %></button>

app/views/post/dashboard.html.erb
<h1>Dashboard</h1>
<hr>

<form method="get" action="/post/create">
   <p>Titulo    : <input name="title"></p>
   <p>Contenido : <textarea name="content"></textarea></p>
   <p>Url imagen: <input name="image_url"></p>
   <input type="submit" value="Enviar">
   <button type="button"><%= link_to "Ir al Posteos", root_path %></button>

</form>

app/views/post/index.html.erb
<h1>Posteos del Blog...</h1>
<hr>
<button type="button"><%= link_to "Crear Post", post_dashboard_path	 %></button>
<hr>
<% @posts.each do |post| %>
   <p><b><%= post.title %></b> </p>
   <p>Fecha: <%= post.created_at.strftime("%d/%m/%Y") %> </p>
   <p>Hora: <%= post.created_at.strftime("%k:%M:%S") %> </p>
   <p>Contenido: <%= post.content %> </p>
   <p>Imagen:</p>
   <%= image_tag(post.image_url, :size => "80x80") %> 
   <hr>
<% end %>